export {
  OUTPUT_SPECS,
  DEFAULT_FPS,
  MIN_DURATION_MS,
  MAX_DURATION_MS,
  DEFAULT_CLIP_DURATION_MS,
  MIN_CLIP_DURATION_MS,
  MAX_CLIP_DURATION_MS,
  DEFAULT_TRANSITION_DURATION_MS,
  MIN_TRANSITION_DURATION_MS,
  MAX_TRANSITION_DURATION_MS,
} from './instagram';

export {
  DEFAULT_CANVAS_CONFIG,
  DEFAULT_EXPORT_CONFIG,
  MAX_WORKING_RESOLUTION,
  MAX_CLIPS,
  AUTO_SAVE_DEBOUNCE_MS,
  DEFAULT_AUDIO_FADE_MS,
  DEFAULT_AUDIO_VOLUME,
  THUMBNAIL_SIZE,
  MIN_TOUCH_TARGET,
} from './defaults';

export {
  MOTION_PRESETS,
  getRandomPreset,
  getPresetById,
  configFromPreset,
} from './presets';
